### ISSUE TITLE
portal

### ISSUE THREAD

**Issue by ghost** [samerton/Nameless-Bootstrap-Material-Design#3]
portal for material design if i try to activate i get 'Placeholder - use this template for your own custom portal.'
I hope you can add animations too with matirial design like https://jartexnetwork.com/

**Comment by ghost** [comment]
When i will get a response?

**Comment by ghost** [comment]
You can download external portals from spigot

**Comment by samerton** [comment]
Unfortunately I'm not planning on developing a portal for this template, it's intended that you use your own portal instead.
