### ISSUE TITLE
Incorrect Social Icons

### ISSUE THREAD

**Issue by DevScyu** [samerton/Nameless-Bootstrap-Material-Design#8]
![image](https://user-images.githubusercontent.com/15234414/91672210-f7fb1a00-eb24-11ea-9850-3ea356a10c8b.png)

This is meant to be the youtube social icon, according to font awesome, this falls under their "Brands" section, `<i class="fab fa-youtube-square"></i>` but the footer contains `<i id="social-gp" class="fa fa-youtube-square fa-3x social"></i>`
**Note**: `fa fa-youtube-square` instead of `fab fa-youtube-square` 

(This applies to all of the "social" icons)

**Comment by samerton** [comment]
Thanks for raising + for the PR! I've left a comment on the PR to account for sites which may be installed in a subdirectory 👍
